Feature/implement room and retrofit/arc 675
ted3x/MovieApp pull request #2
Opened 2020-10-28 13:47 UTC by ted3x

2020-10-28 19:33 UTC, DavitSoitashviliSpace requested changes

2020-10-28 19:47 UTC, ted3x commented on app/src/main/java/com/c0d3in3/movieapp/data/remote/ApiService.kt
> +
I think it's better to have these two functions splitted, than having another parameter to divide them.

2020-10-28 20:02 UTC, ted3x commented on app/src/main/java/com/c0d3in3/movieapp/data/remote/ApiService.kt
> +
Changed.

2020-10-28 20:03 UTC, ted3x commented on app/src/main/java/com/c0d3in3/movieapp/models/network/Movie.kt
> +    val popularity : Double,
Added nullable types.

2020-10-28 20:03 UTC, ted3x commented on app/src/main/java/com/c0d3in3/movieapp/data/remote/RetrofitClient.kt
> +}
Changed

2020-10-29 06:30 UTC, Edna001 approved these changes

2020-10-29 07:11 UTC, DavitSoitashviliSpace approved these changes

2020-11-01 06:24 UTC, merged