Fix/fix shared viewmodel
ted3x/MovieApp pull request #8
Opened 2020-11-15 19:27 UTC by ted3x

Created BaseFragment abstract class, where I handle all network connectivity and opening detailed movie.
Now MovieAdapter uses lambda expression instead of interface with one method.
App doesn't use shared view models, since it's useless.
now Fragments can change UI based on connectivity.
ConnectivityReceiver now uses lambda as well instead of interface.

2020-11-17 11:36 UTC, Edna001 requested changes

2020-11-17 11:36 UTC, Edna001 commented on app/src/main/java/com/c0d3in3/movieapp/BaseFragment.kt
> +        navController.navigate(R.id.action_moviesDashboardFragment_to_movieDetailFragment,bundle)
remake this bundle like bundleOf

2020-11-17 11:36 UTC, Edna001 commented on app/src/main/java/com/c0d3in3/movieapp/ui/movie_detail_screen/MovieDetailFragment.kt
> +            viewModel = ViewModelProvider(it)[MovieDetailViewModel::class.java]
this should be in onCreate() method

2020-11-17 11:36 UTC, Edna001 commented on app/src/main/java/com/c0d3in3/movieapp/ui/movie_detail_screen/MovieDetailFragment.kt
> +        viewModel.loadMovie(requireArguments().getInt("movieId"))
this should be in onViewCreated() method

2020-11-17 12:12 UTC, DavitSoitashviliSpace requested changes

2020-11-17 12:24 UTC, ted3x commented on app/src/main/java/com/c0d3in3/movieapp/BaseFragment.kt
> +        navController.navigate(R.id.action_moviesDashboardFragment_to_movieDetailFragment,bundle)
Changed

2020-11-17 12:24 UTC, ted3x commented on app/src/main/java/com/c0d3in3/movieapp/ui/movie_detail_screen/MovieDetailFragment.kt
> +            viewModel = ViewModelProvider(it)[MovieDetailViewModel::class.java]
Changed

2020-11-17 12:24 UTC, ted3x commented on app/src/main/java/com/c0d3in3/movieapp/ui/movie_detail_screen/MovieDetailFragment.kt
> +        viewModel.loadMovie(requireArguments().getInt("movieId"))
Changed

2020-11-17 12:24 UTC, ted3x commented on app/src/main/java/com/c0d3in3/movieapp/ui/movie_detail_screen/MovieDetailViewModel.kt
> +            withContext(Dispatchers.IO){
Changed

2020-11-17 12:24 UTC, ted3x commented on app/src/main/java/com/c0d3in3/movieapp/ui/movie_detail_screen/MovieDetailViewModel.kt
> +            withContext(Dispatchers.IO) {
Changed

2020-11-17 12:24 UTC, ted3x commented on app/src/main/java/com/c0d3in3/movieapp/ui/movie_detail_screen/MovieDetailViewModel.kt
> +                selectedMovie.value?.let {
Changed

2020-11-17 12:30 UTC, DavitSoitashviliSpace approved these changes

2020-11-18 16:16 UTC, Edna001 approved these changes

2020-11-26 08:31 UTC, merged